@startuml

enum Role {
  ROLE_ADMIN
  ROLE_EMPLOYEE
  ROLE_CLIENT
}

class User {
    - id : Long
    - username : String
    - password : String
    - email : String
    - emailVerified : boolean

    + User(username, password, role, name, surname, email, age, address, photo) 
    + setEmailVerified()
}

User --> Role : tiene

@enduml
